spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pets
    username: "root"
    password: "#3eLcDms2024*"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true